/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_TYPES_H
#define test_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace THRIFT {

class Error;

typedef struct _Error__isset {
  _Error__isset() : _message(false) {}
  bool _message :1;
} _Error__isset;

class Error : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  Error(const Error&);
  Error& operator=(const Error&);
  Error() : _message() {
  }

  virtual ~Error() throw();
  std::string _message;

  _Error__isset __isset;

  void __set__message(const std::string& val);

  bool operator == (const Error & rhs) const
  {
    if (!(_message == rhs._message))
      return false;
    return true;
  }
  bool operator != (const Error &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Error & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Error& obj);
};

void swap(Error &a, Error &b);

} // namespace

#endif
